### ISSUE TITLE
Rejected by jkup

### ISSUE THREAD

**Issue by hinell** [Rejectedus/rejected.us#253]
Surprisingly, I just found that I ([@biteofpie](https://twitter.com/biteofpie)) was rejected by @jkup himself on twitter :tada:.

![image](https://user-images.githubusercontent.com/8136158/197336001-318c518f-4802-4296-8361-dc7ba8ce1219.png)

The story is worth telling! :smirk:

**Comment by jkup** [comment]
I have literally no idea! I almost never block people. Perhaps it was a misclick? Corrected (and sorry!)
